### ISSUE TITLE
Fix diacritic characters in path causing directory not found

### ISSUE THREAD

**Issue by Apollys** [Apollys/PoEDynamicLootFilter#15]
Steps to replicate:
1. Create a directory somewhere named `TestPathOfExileDirectory_á`
2. Run `setup.py`, and when prompted for the Path of Exile directory, enter the path to the above folder.
3. Receive the following error message: `RuntimeError: Path of Exile directory: "...\TestPathOfExileDirectory_Ã¡" does not exist`

Demonstration of core problem:
```
>>> s = 'á'
>>> ''.join(chr(i) for i in s.encode('utf-8'))
'Ã¡'
```

Python strings are represented as sequences of unicode values.  When unicode strings are encoded as byte strings (UTF-8 encoding), any non-ASCII characters must be converted into multiple bytes.  Specifically here, `á`'s encoding equals the concatenation of the two bytes `Ã¡`.

So, somewhere paths are being converted into bytestrings.  My guess would be it has to do with `os.path` calls.  We need to isolate this and force strings to stay in the unicode format, or use UTF-32 if encoding is required.

**Comment by MarkKoz** [comment]
`os.path` is not the problem (though `pathlib` is nicer IMO anyway). The problem is that you rely on `os.system`:

https://github.com/Apollys/PoEDynamicLootFilter/blob/a7735ce79a7c960962b476764ca5462be3ee33d7/setup.py#L182

`os.system` should generally be avoided since it spawns a shell and then executes the given command within the shell. Not only is this shell middleman often unnecessarily wasteful, it also has a bunch of side effects, including being affected by the system's encoding or "code page". The encoding is locale-dependent and does not support Unicode unless enabled explicitly here:

![bild](https://user-images.githubusercontent.com/1515135/171791069-954bd265-350a-4006-b450-59037e98d655.png)

You could change it to use `subprocess.run` instead (with `shell=False`). However, it seems unnecessary in this case to use a separate process to execute Python code when you're already executing Python code. You could instead import the module and call a function inside it to do the same thing, which is much simpler.

**Comment by Apollys** [comment]
Thanks for looking into this! I don't recall why I originally changed to UTF-8 encoding now.

Do you think there is any problem with sticking to the default encoding everywhere?

**Comment by MarkKoz** [comment]
> Do you think there is any problem with sticking to the default encoding everywhere?

It's generally considered best practice to explicitly specify an encoding because it makes for consistent results across systems. For this specific issue, it's fine to change the config to be read as UTF-8, since that's already what was used to write the config. However, changing encodings elsewhere may cause issues for users that upgrade since they will have files written using the previous encoding. If you were to change configs to be written with the default encoding, that wouldn't fix the configs that were already encoded as UTF-8.

**Comment by Apollys** [comment]
That's a good point, I don't want to break any configs that already exist.

Thanks for your PR also by the way. I just wanted to change it in a different spot in the code, so I'll push my own.  Regardless, I really appreciate the initiative you took to debug and fix this issue!

**Comment by Apollys** [comment]
Fixed as per MarkKoz's suggestion.

**Comment by MarkKoz** [comment]
> That's a good point, I don't want to break any configs that already exist.
> 
> Thanks for your PR also by the way. I just wanted to change it in a different spot in the code, so I'll push my own. Regardless, I really appreciate the initiative you took to debug and fix this issue!

You're welcome. I think we both changed the same spot, but I seemed to have missed one spot that you caught.
