### ISSUE TITLE
Some currency gets mis-tiered on import

### ISSUE THREAD

**Issue by indivisible** [Apollys/PoEDynamicLootFilter#16]
For example chromatic orbs get completely hidden when importing a neversink very-strict filter from filterblade (where they're shown in 3+ stack size)

I like the simpler tiering concept of the program, but it seems very hard to correctly map to filterblade, which has multiple tier definitions based on stack sizes

**Comment by TwiliteDream** [comment]
This isn't a bug with Dynamic Loot Filter, it's an issue with the base NeverSink filter. NeverSink has 9 default tiers of currencies (plus 2 bonus for portals and wisdoms), and each of those 9 currency tiers has 3 (or more) rules -- 1 for individual drops, 1 for 3+ stack drops, and 1 for 6+ stack drops. Some lower tiers have rules for 10+ stack drops.

The problem is that in NeverSink Very Strict BASE FILTER (0 changes), Chromatic Orbs are listed as a T7 currency (which is called Mid Tier 2, and has things like chance and jeweler's orbs). However, stacks of Chromatic Orbs are treated as stacks of T5 currency (which has things like stacks of Vaal and Fusing orbs). This is pretty clearly a logical inconsistency that needs to be remedied before DLF can be applied to the filter.

So, when DLF First imports your filter it applies strict tier compliance -- that means that if Chromatic orbs are T7 currencies then stacks of chromatic orbs will become stacks of T7 currencies. This will cause some discrepancies with NeverSink, because their tiers are horrifically inconsistent.
